### ISSUE TITLE
Improve the canonical docker-compose setup

### ISSUE THREAD

**Issue by spawnia** [passwork-me/docker#1]
I have created a docker-compose based setup for passwork a while ago, since the plain Docker setup was hard to manage for me.

https://github.com/mll-lab/passwork-docker-compose

I see you recently started supporting a docker-compose based setup yourself. How do you feel about combining the best of both to create a properly supported, stable and well documented setup in this repo?

**Comment by fackyhigh** [comment]
Hello, what do you mean by Improve the canonical docker-compose setup? Could you describe in more detail?
We liked your setup.sh script. If you are not opposed, we will implement it.

**Comment by spawnia** [comment]
This repository does seem to hold useful configuration files, but there is no documentation at all. As a user, i would expect a `README.md` that contains information about how it can be used.

As of now, i am not even sure what the purpose of this repository is. Do you mean for it to be used to install Passwork?

**Comment by spawnia** [comment]
I think it would be a great idea for Passwork to offer a well-documented, official docker-compose based installation. I am totally fine if that is based upon my setup or uses elements thereof.

Ultimately, i would like to retire https://github.com/mll-lab/passwork-docker-compose and rather consolidate the efforts into an official setup.

**Comment by garakh** [comment]
@spawnia we use this repository to provide an environment for our Docker images which are used to run Passwork in Docker. Passwork is not an open-source project. You can find a comprehensive manual in our knowledge database (https://www.notion.so/passwork/Docker-2335c8f6cb8f4890bedd6757b54ecff8). We will explain it in Readme soon.

Passwork Docker Images are not tailored to Passwork as a product. So it is a quite independent environment where you can run PHP sites with PhalconPHP, MongoDB, Postfix, and set up any config files as you might wish. I suppose we might publish it as a public opensource project but not now, maybe later.
